name: Build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [
          10,
          12,
          14,
        ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm ci
      - name: Check formatting with prettier
        run: |
          npx prettier -u -c examples lib
      - name: Lint with eslint
        run: |
          npm run lint
      - name: Run unit tests
        run: |
          npm run test
